### PR TITLE
Removes use of deprecated methods

### PR DESCRIPTION
**Pull request by JamoBox**
This Pull Request removes (hopefully all, unless I missed any) uses of deprecated methods in the library.
##### Some key things to note:
- To make it possible for the library users to send raw data without using deprecated methods, the IrcPacket(String, IrcConnection) constructor has been made `public`.
- Deprecated methods should now be fit for removal when you see fit as there are no longer any internal calls to them.
- This branch should be merged into `master` once approved, and the `io` branch closed.

### CODE REVIEW

**Comment by sorcix** [comment]
I'm on holiday and only have my phone at this time. I'll check it out when
I get back around Jan 3rd.

**Comment by JamoBox** [comment]
Alright, I'll try and get it working before then if possible, if not I'm sure you'd be able to figure it out when you're back. hope you're having a good time

**Comment by sorcix** [comment]
The tests fail because it compares the IrcPacket instance and not the values inside. (The instance created as expected test result is not the same one as the one sIRC creates.) I think an Equals method on IrcPacket will fix this, should have more time next weekend to look into this.

**Comment by JamoBox** [comment]
Ah, that would make sense. I'm not as familiar as I should be with JUnit
and never used mockito, so I was a little confused by it.

**Comment by sorcix** [comment]
I have merged some of your commits already. I'm waiting with the deprecated methods because your changes would render the Unit tests a bit useless: the correct formatting by the IrcPacket class is no longer covered.

So I will write a JUnit test for IrcPacket first, when that is tested we can use the class in other tests.

**Comment by JamoBox** [comment]
Sounds ideal

**Pull request closed without merging**
